---
- hosts: localhost
  connection: local

  tasks:
  - name: create ansible_distribution group
    group_by: key={{ ansible_distribution }}

  - name: create ansible_distribution group
    group_by: key={{ ansible_os_family }}

  - name: create ansible_pkg_mgr group
    group_by: key={{ ansible_pkg_mgr }}
